/// Tables that participate in sync with the remote API.
pub const SYNCED_TABLES: &[&str] = &[
    "shortcuts",
    "sql_table_analyzer_templates",
    "sql_macrosing_templates",
    "note_folders",
    "notes",
    "obfuscation_mappings",
    "snippet_tags",
    "task_categories",
    "task_statuses",
    "tasks",
    "task_checkboxes",
    "task_links",
    "finance_plans",
    "finance_items",
    "finance_payments",
    "finance_import_batches",
    "finance_transactions",
    "finance_mapping_rules",
    "finance_transaction_allocations",
];

/// Columns present on every synced table (uuid, updated_at, sync_status, user_id).
pub const SYNC_FIELDS: &[&str] = &["uuid", "updated_at", "sync_status", "user_id"];

/// Returns the data-only columns for a synced table (excluding sync fields and `id`).
/// These match the Python `sync_schema.SYNCED_TABLES[table]['data_fields']` minus `id`.
pub fn data_columns(table: &str) -> &'static [&'static str] {
    match table {
        "shortcuts" => &[
            "name",
            "value",
            "description",
            "links",
            "obsidian_note",
            "is_pinned",
            "pinned_sort_order",
        ],
        "sql_table_analyzer_templates" => &["template_text"],
        "sql_macrosing_templates" => &[
            "template_name",
            "template_text",
            "placeholders_config",
            "combination_mode",
            "separator",
        ],
        "note_folders" => &["name", "sort_order", "parent_id"],
        "notes" => &[
            "folder_id",
            "title",
            "content",
            "created_at",
            "is_pinned",
            "pinned_sort_order",
        ],
        "obfuscation_mappings" => &[
            "session_name",
            "entity_type",
            "original_value",
            "obfuscated_value",
            "created_at",
        ],
        "snippet_tags" => &["name", "patterns", "color", "sort_order"],
        "task_categories" => &["name", "color", "sort_order", "created_at"],
        "task_statuses" => &["name", "color", "sort_order", "created_at"],
        "tasks" => &[
            "title",
            "category_id",
            "status_id",
            "is_pinned",
            "bg_color",
            "tracker_url",
            "notes_md",
            "sort_order",
            "created_at",
        ],
        "task_checkboxes" => &[
            "task_id",
            "parent_id",
            "text",
            "is_checked",
            "sort_order",
            "created_at",
        ],
        "task_links" => &["task_id", "url", "label", "sort_order", "created_at"],
        "finance_plans" => &["name", "currency", "kind", "sort_order", "created_at"],
        "finance_items" => &[
            "plan_id",
            "parent_id",
            "name",
            "amount_cents",
            "due_day",
            "due_date",
            "note",
            "sort_order",
            "created_at",
        ],
        "finance_payments" => &[
            "plan_id",
            "item_id",
            "month_key",
            "is_paid",
            "paid_amount_cents",
            "note",
            "created_at",
        ],
        "finance_import_batches" => &[
            "source",
            "file_name",
            "total_rows",
            "imported_rows",
            "duplicate_rows",
            "error_rows",
            "date_from",
            "date_to",
            "expense_total_cents",
            "income_total_cents",
            "currency",
            "created_at",
        ],
        "finance_transactions" => &[
            "source",
            "source_fingerprint",
            "import_batch_id",
            "operation_at",
            "payment_date",
            "card_mask",
            "status",
            "amount_cents",
            "currency",
            "operation_amount_cents",
            "operation_currency",
            "payment_amount_cents",
            "payment_currency",
            "cashback_cents",
            "bank_category",
            "mcc",
            "description",
            "bonuses_cents",
            "invest_rounding_cents",
            "rounded_amount_cents",
            "raw_json",
            "rules_locked",
            "created_at",
        ],
        "finance_mapping_rules" => &[
            "name",
            "is_enabled",
            "priority",
            "match_mode",
            "conditions_json",
            "target_plan_id",
            "target_item_id",
            "created_at",
        ],
        "finance_transaction_allocations" => &[
            "transaction_id",
            "plan_id",
            "item_id",
            "assigned_by",
            "rule_id",
            "is_active",
            "created_at",
        ],
        _ => &[],
    }
}

/// All columns stored in a synced table (data + sync fields), excluding `id`.
pub fn all_columns(table: &str) -> Vec<&'static str> {
    let mut cols: Vec<&str> = data_columns(table).to_vec();
    // sync fields except sync_status (which is managed locally)
    cols.extend_from_slice(&["uuid", "updated_at", "user_id"]);
    cols
}
